export const STUDY_STATES = {
  studyIntro: 'study-intro',
  termsAndPolicy: 'terms-and-policy',
  allowCamera: 'allow-camera',
  calibrationInstructions: 'calibration-instructions',
  studyCalibration: 'study-calibration',
  faceBox: 'face-box',
  acceptFullScreen: 'accept-full-screen',
  resultCalibration: 'result-calibration',
  studyStimulus: 'study-stimulus',
  finalMessage: 'final-message',
  loader: 'loader',
  missingParams: 'missing-params',
  hardwareAccelerationDisabled: 'hardware-acceleration-disabled',
  alreadyAnswered: 'already-answered',
  printScreen: 'print-screen',
  faceWithoutDetection: 'face-without-detection',
  waitingAlignmentOfFaceAndEyes: 'waiting-alignment-of-face-and-eyes',
  allowPopup: 'allow-popup',
} as const
